---
- name: Task 11 Creating Custom Facts
  hosts:  dev
  tasks:
    - name: Create the facts.d directory
      file:
        path: /etc/ansible/facts.d
        owner: automation
        state: directory

    - name: Copy cool.fact to the facts.d directory
      copy:
        src: custom.fact
        dest: /etc/ansible/facts.d

    - name: Inspect the custom fact
      setup:
        filter: ansible_local
      register: myfact

    - name: Show the fact to me
      debug:
        msg: The fact is {{ myfact.ansible_facts.ansible_local.custom.sample_exam }}
