---
- name: Task 13 Software Repositories
  hosts: node1
  vars: 
    - pkg_name: zabbix-agent
  tasks:
    - name: Add repository
      yum_repository:
        name: "zabbix-monitoring"
        description: "Zabbix 5.2 Repo"
        file: zabbix.repo
        baseurl: https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/
        enabled:  yes
        gpgcheck: no

    - name: Install the zabbix-agent package 
      yum:
        name: zabbix-agent
        state: present

    - name: Gather the rpm package facts
      package_facts:
        manager: auto


    - name: Display zabbix-agent package facts
      debug:
        var: ansible_facts.packages[pkg_name]
      when: pkg_name in ansible_facts.packages



