---
- name: Task 8 Using RHEL System Roles
  hosts:  dev
  vars:
    selinux_booleans:
      - { name: 'httpd_can_network_connect', state: 'on', persistent: 'yes' }
  tasks:
    - name: execute the role and catch errors
      block:
        - include_role:
            name: rhel-system-roles.selinux
      rescue:
        # Fail if failed for a different reason than selinux_reboot_required.
        - name: handle errors
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: restart managed host
          reboot:
            msg: "system is rebooting"

        - name: reapply the role
          include_role:
            name: rhel-system-roles.selinux
