---
- name: SSH daemon
  hosts:  node1
  tasks:
    - name: 
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          banner /etc/motd
          X11Forwarding no
          MaxAuthTries 3
      notify: start_ssh

  handlers:
    - name: start_ssh
      service:  
        name: sshd
        state: restarted    
